"""billing meters and outbox

Revision ID: 876062a85221
Revises: 384be6596b36
Create Date: 2026-06-25 21:43:20.163112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '876062a85221'
down_revision: Union[str, None] = '384be6596b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'sent', 'failed', name='outbox_status').create(op.get_bind())
    sa.Enum('allow', 'cap', 'block', name='overage_policy').create(op.get_bind())
    op.create_table('billing_event_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recompute_seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'sent', 'failed', name='outbox_status', create_type=False), server_default=sa.text("'pending'::outbox_status"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_status_created', 'billing_event_outbox', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_billing_event_outbox_transaction_id'), 'billing_event_outbox', ['transaction_id'], unique=True)
    op.add_column('organization_usage_cycles', sa.Column('used_voice_minutes', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.add_column('organization_usage_cycles', sa.Column('used_ai_cost_cents', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.add_column('organization_usage_cycles', sa.Column('allowance_voice_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('organization_usage_cycles', sa.Column('allowance_ai_cost_cents', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('organizations', sa.Column('lago_customer_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('billing_plan_code', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('overage_policy', postgresql.ENUM('allow', 'cap', 'block', name='overage_policy', create_type=False), server_default=sa.text("'block'::overage_policy"), nullable=False))
    op.add_column('organizations', sa.Column('overage_cap_pct', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('included_voice_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('organizations', sa.Column('included_ai_cost_cents', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('organizations', sa.Column('billing_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'billing_suspended')
    op.drop_column('organizations', 'included_ai_cost_cents')
    op.drop_column('organizations', 'included_voice_minutes')
    op.drop_column('organizations', 'overage_cap_pct')
    op.drop_column('organizations', 'overage_policy')
    op.drop_column('organizations', 'billing_plan_code')
    op.drop_column('organizations', 'lago_customer_id')
    op.drop_column('organization_usage_cycles', 'allowance_ai_cost_cents')
    op.drop_column('organization_usage_cycles', 'allowance_voice_minutes')
    op.drop_column('organization_usage_cycles', 'used_ai_cost_cents')
    op.drop_column('organization_usage_cycles', 'used_voice_minutes')
    op.drop_index(op.f('ix_billing_event_outbox_transaction_id'), table_name='billing_event_outbox')
    op.drop_index('idx_outbox_status_created', table_name='billing_event_outbox')
    op.drop_table('billing_event_outbox')
    sa.Enum('allow', 'cap', 'block', name='overage_policy').drop(op.get_bind())
    sa.Enum('pending', 'sent', 'failed', name='outbox_status').drop(op.get_bind())
    # ### end Alembic commands ###
